### ISSUE TITLE
Column / card widths

### ISSUE THREAD

**Issue by cfdesign** [ivanteso/portfolio#1]
Hello Ivan, it is Chris from Udacity. 

I am currently learning how to use GIT and GitHub so I thought I would take this opportunity to test out my skills in this area.

I forked your portfolio and made the suggested changes in a separate branch. I thought maybe you would like to see what I was trying to explain with the flex-box property `space-between` and relative spacing by % of the window width.

**Comment by ivanteso** [comment]
Hi Chris! I've checked your modify and I merged your pull request :D I'll follow the course you were talking about ASAP ;) 
Thank you again!

**Comment by cfdesign** [comment]
You are always welcome. As I said it is a very minimal contribution, I mainly wished to practise using this whole GIT/GitHub thing! 

Thanks for sharing your portfolio design with us all. See you on Slack!

**Comment by ivanteso** [comment]
Well you made me practice too @cfdesign , so it's even more appreciated 😄 
At for what concern the portfolio design your suggestion was 100% accurate. I really like the new columns' layout 👌
